server:
  port: 8989
  servlet:
    context-path: /springboot-elastic
spring:
  # es的Jest操作
  elasticsearch:
    jest:
      uris: http://192.168.139.22:9200
  # es的springboot-data操作
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.139.22:9300